package com.odk.Enum;

public enum StatutCourrier {
    RECU,   //Courrier Affecter à la direction...
    IMPUTER,  //Courrier imputé (envoyerOupartager) à une entité ou département...
    EN_COURS, //Courrier en cours de traitement...
    TRAITER,    //Courrier traité...
    ARCHIVER     //Courrier Archiver...   
}
