package com.odk.Enum;

public enum StatutCourrier {
    ENVOYER,   //Courrier envoyé/reçu
    IMPUTER,  //Courrier imputé (envoyerOupartager) à une entité ou département...
    EN_COURS, //Courrier en cours de traitement...
    ARCHIVER,     //Courrier Archiver...
    REPONDU
}